name: Build and deploy

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and publish to registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: marcinggalinski/md-reactionist
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}
          dockerfile: Dockerfile
          tags: latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: Production
    steps:
      - name: Deploy container to server
        uses: appleboy/ssh-action@master
        env:
          GITHUB_USERNAME: ${{github.repository_owner}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          MD_BOT_TOKEN: ${{secrets.DISCORD_BOT_TOKEN}}
        with:
          host: ${{secrets.DEPLOY_HOST}}
          username: ${{secrets.DEPLOY_USERNAME}}
          password: ${{secrets.DEPLOY_PASSWORD}}
          envs: GITHUB_USERNAME, GITHUB_TOKEN, MD_BOT_TOKEN
          script: |
            docker login ghcr.io -u $GITHUB_USERNAME -p $GITHUB_TOKEN
            docker pull ghcr.io/marcinggalinski/md-reactionist:latest
            docker logout ghcr.io
            docker ps -q --filter "name=md-reactionist" | xargs -r docker stop    # stop container if running
            docker ps -aq --filter "name=md-reactionist" | xargs -r docker rm     # remove container if exists
            docker run -d -e MD_BOT_TOKEN=$MD_BOT_TOKEN --restart=always --name md-reactionist md-reactionist

